sudo: required
services:
    - docker

before_install:
  - docker image build -t mwiesbau/docker-react -f Dockerfile.dev .


script:
  - docker container run mwiesbau/docker-react npm run test -- --coverage