sudo: required
services:
    - docker

before_install:
  - docker image build -t mwiesbau/docker-react -f Dockerfile.dev .


script:
  - docker container run -e CI=true mwiesbau/docker-react npm run test -- --coverage